### ISSUE TITLE
UncaughtException ErrorException with message include(php://filter....

### ISSUE THREAD

**Issue by aftabnaveed** [goaop/goaop-laravel-bridge#4]
I am trying to create my provider using php artisan make:provider AopServiceProvider, but I get this error

php artisan make:provider AopServiceProvider

```
Fatal error: Uncaught exception 'ErrorException' with message 'include(php://filter/read=go.source.transforming.loader/resource=/var/www/html/app/Exceptions/Handler.php): File not found' in /var/www/html/vendor/goaop/framework/src/Instrument/ClassLoading/AopComposerLoader.php:136
Stack trace:
#0 /var/www/html/vendor/goaop/framework/src/Instrument/ClassLoading/AopComposerLoader.php(136): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 (): Go\Instrument\ClassLoading\AopComposerLoader->loadClass()
#2 (): ReflectionClass->__init()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(749): ReflectionClass->__construct()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(644): Illuminate\Container\Container->build()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(709): Illuminate\Container\Container->make()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(231): Illuminate\Foundation\Application->make()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(746): Closure$Illuminate\Container\Container::getClosure()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(644): Illuminate\Container\Container->build()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(709): Illuminate\Container\Container->make()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1203): Illuminate\Foundation\Application->make()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(320): Illuminate\Container\Container->offsetGet()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(123): Illuminate\Foundation\Console\Kernel->reportException()
#13 /var/www/html/artisan(36): Illuminate\Foundation\Console\Kernel->handle()
#14 {main}
Exception handler threw an object exception: exception 'ErrorException' with message 'include(php://filter/read=go.source.transforming.loader/resource=/var/www/html/app/Exceptions/Handler.php): File not found' in /var/www/html/vendor/goaop/framework/src/Instrument/ClassLoading/AopComposerLoader.php:136
Stack trace:
#0 /var/www/html/vendor/goaop/framework/src/Instrument/ClassLoading/AopComposerLoader.php(136): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 (): Go\Instrument\ClassLoading\AopComposerLoader->loadClass()
#2 (): ReflectionClass->__init()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(749): ReflectionClass->__construct()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(644): Illuminate\Container\Container->build()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(709): Illuminate\Container\Container->make()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(231): Illuminate\Foundation\Application->make()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(746): Closure$Illuminate\Container\Container::getClosure()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(644): Illuminate\Container\Container->build()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(709): Illuminate\Container\Container->make()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(154): Illuminate\Foundation\Application->make()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(79): Illuminate\Foundation\Bootstrap\HandleExceptions->getExceptionHandler()
#12 (): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException()
#13 {main}

```

**Update**
This works with php 7.1 but not with HHVM 3.15.

**Comment by lisachenko** [comment]
Hi! Could you please check if the file `/var/www/html/app/Exceptions/Handler.php` is exists?

**Comment by aftabnaveed** [comment]
Sorry for the late response @lisachenko  Yes the file exists in that location.

**Comment by aftabnaveed** [comment]
I was able to temporarily fix it by commenting line 163 of vendor/goaop/framework/src/Instrument/ClassLoading/AopComposerLoader.php file

**Comment by lisachenko** [comment]
I noticed, that you mentioned HHVM: it's impossible to use framework fully under HHVM right now without cache. So, framework can run the code under HHVM with prepared cache, but can not work normally without the cache.

**Comment by lisachenko** [comment]
See https://github.com/facebook/hhvm/issues/6834 for additional details why it isn't working under HHVM.

**Comment by lisachenko** [comment]
I'm going to drop HHVM support. Currently, all big projects decided to drop HHVM too, see my post and related threads: https://github.com/goaop/framework/issues/143#issuecomment-306840301

Time to switch to PHP7.x and receive better performance and reliable behaviour. Thanks!
